### ISSUE TITLE
Feature request: Selective content_entry sync and deploy

### ISSUE THREAD

**Issue by banditrider** [locomotivecms/wagon#359]
We'd like to specify a content_entry slug to sync and deploy content_entries only belonging to this content_type. Bonus: additionally being able to specify content_entries slugs to sync/deploy specific content entries.

I tried using -f which doesn't seem to be implemented on sync.

**Comment by did** [comment]
The way sync works now is that it fetches all the content (and only the content) from the env you picked. It works pretty well for sites with not a ton of assets.
The problem with targeting only a content entry slug is that this content entry can be related to other content types and so it's not that easy to get the content dependencies. That's why we prefer to get everything.
